export const kanaData = [
  // Hiragana
  { character: 'あ', romaji: 'a', type: 'hiragana' },
  { character: 'い', romaji: 'i', type: 'hiragana' },
  { character: 'う', romaji: 'u', type: 'hiragana' },
  { character: 'え', romaji: 'e', type: 'hiragana' },
  { character: 'お', romaji: 'o', type: 'hiragana' },
  { character: 'か', romaji: 'ka', type: 'hiragana' },
  { character: 'き', romaji: 'ki', type: 'hiragana' },
  { character: 'く', romaji: 'ku', type: 'hiragana' },
  { character: 'け', romaji: 'ke', type: 'hiragana' },
  { character: 'こ', romaji: 'ko', type: 'hiragana' },
  // Katakana
  { character: 'ア', romaji: 'a', type: 'katakana' },
  { character: 'イ', romaji: 'i', type: 'katakana' },
  { character: 'ウ', romaji: 'u', type: 'katakana' },
  { character: 'エ', romaji: 'e', type: 'katakana' },
  { character: 'オ', romaji: 'o', type: 'katakana' },
  { character: 'カ', romaji: 'ka', type: 'katakana' },
  { character: 'キ', romaji: 'ki', type: 'katakana' },
  { character: 'ク', romaji: 'ku', type: 'katakana' },
  { character: 'ケ', romaji: 'ke', type: 'katakana' },
  { character: 'コ', romaji: 'ko', type: 'katakana' },
  // Dakuon (Hiragana with dakuten)
  { character: 'が', romaji: 'ga', type: 'dakuon' },
  { character: 'ぎ', romaji: 'gi', type: 'dakuon' },
  { character: 'ぐ', romaji: 'gu', type: 'dakuon' },
  { character: 'げ', romaji: 'ge', type: 'dakuon' },
  { character: 'ご', romaji: 'go', type: 'dakuon' },
  // Handakuon
  { character: 'ぱ', romaji: 'pa', type: 'dakuon' },
  { character: 'ぴ', romaji: 'pi', type: 'dakuon' },
  { character: 'ぷ', romaji: 'pu', type: 'dakuon' },
  { character: 'ぺ', romaji: 'pe', type: 'dakuon' },
  { character: 'ぽ', romaji: 'po', type: 'dakuon' },
  // Yoon (Hiragana with combination sounds)
  { character: 'きゃ', romaji: 'kya', type: 'yoon' },
  { character: 'きゅ', romaji: 'kyu', type: 'yoon' },
  { character: 'きょ', romaji: 'kyo', type: 'yoon' },
  { character: 'しゃ', romaji: 'sha', type: 'yoon' },
  { character: 'しゅ', romaji: 'shu', type: 'yoon' },
  { character: 'しょ', romaji: 'sho', type: 'yoon' },
];
